# =============== Hyperparameters ===============

# Number of datasets to generate. Results will be aggregated over these datasets.
n_datasets : 10

# The proportion of the data points to use for validation prediction.
val_proportion : 0.2

# Whether to do validation prediction
do_val : True



# =============== Logging ===============
do_wandb : False
wandb_config:
  project : Bayesian Sparse Regression
do_tb : True
do_cli : True
do_tqdm : True



# =============== Dataset and regressor method, and Hydra parameters ===============
defaults:
  - _self_
  - dataset : mean
  - regressor : random
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled 


# Hydra config, do not change.
hydra:
  output_subdir: null
  run:
    dir: .